source 'https://github.com/CocoaPods/Specs.git'
platform :macos, '10.11'

use_frameworks!
swift_version = '4.0'

target :'FBSnapshotTestCaseDemoMacOSTests' do
  pod 'iOSSnapshotTestCase', :path => '..'
end
