source 'https://github.com/CocoaPods/Specs.git'

target 'FBSnapshotTestCaseDemoMacOS' do
	platform :macos, '10.11'
	use_frameworks!
	swift_version = '4.0'

	pod 'SnapKit'

	target 'FBSnapshotTestCaseDemoMacOSTests' do
		inherit! :search_paths
		pod 'iOSSnapshotTestCase', :path => '..'
	end
end
