platform :ios, '10.0'

def snap 
  pod 'iOSSnapshotTestCase', :path => '../..'
end

target 'FBSnapshotTestCaseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FBSnapshotTestCaseDemo

  target 'FBSnapshotTestCaseDemoTests' do
    inherit! :search_paths
    snap
  end

  target 'FBSnapshotTestCasePreprocessorDemoTests' do
    inherit! :search_paths
    snap
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.1'
    end
  end
end